// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1agfzKqUT8Zr4A4-xr2CVW9JnTUR8654',
    appId: '1:524052578823:web:83b775f39bd18bb05b60a2',
    messagingSenderId: '524052578823',
    projectId: 'frudfluttertutroial',
    authDomain: 'frudfluttertutroial.firebaseapp.com',
    storageBucket: 'frudfluttertutroial.firebasestorage.app',
    measurementId: 'G-RCSFKZ9VGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjkQUlmtPPpYXajj_W-q4_p2W758VWHQI',
    appId: '1:524052578823:android:fd4e900db046afa65b60a2',
    messagingSenderId: '524052578823',
    projectId: 'frudfluttertutroial',
    storageBucket: 'frudfluttertutroial.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoexEeVxaih14zYK0J6_J6HfEff0GUNqY',
    appId: '1:524052578823:ios:83c2c9ffdcb48e415b60a2',
    messagingSenderId: '524052578823',
    projectId: 'frudfluttertutroial',
    storageBucket: 'frudfluttertutroial.firebasestorage.app',
    iosBundleId: 'com.example.onlinedatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoexEeVxaih14zYK0J6_J6HfEff0GUNqY',
    appId: '1:524052578823:ios:83c2c9ffdcb48e415b60a2',
    messagingSenderId: '524052578823',
    projectId: 'frudfluttertutroial',
    storageBucket: 'frudfluttertutroial.firebasestorage.app',
    iosBundleId: 'com.example.onlinedatabase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1agfzKqUT8Zr4A4-xr2CVW9JnTUR8654',
    appId: '1:524052578823:web:bb6d6001d89203fa5b60a2',
    messagingSenderId: '524052578823',
    projectId: 'frudfluttertutroial',
    authDomain: 'frudfluttertutroial.firebaseapp.com',
    storageBucket: 'frudfluttertutroial.firebasestorage.app',
    measurementId: 'G-CJR7D4V456',
  );
}
